orchestrator:
  consumer:
    concurrency: 6
    max-poll-records: 300
    poll-timeout: PT5S
    
  database:
    strategy: RELIABLE
    bulk-size: 500
    
  monitoring:
    enable-metrics: true
    metrics-prefix: mongo-orchestrator

logging:
  level:
    com.orchestrator: INFO
    org.springframework.kafka: WARN
    org.springframework.data.mongodb: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"